### ISSUE TITLE
query construction

### ISSUE THREAD

**Issue by flummingbird** [discoverygarden/islandora_collection_search#13]
I'm using the module at work and everything is fine with the exception of the construction of the solr query:
/islandora/search/dc.title%3A%281946%29?cp=small%3Acollection
                    
notice the 'cp' string before the actual pid. if 'cp' is changed to 'pid' the query works fine. I cannot figure out where cp is being added in the construction of the query for this module. Is it getting cp from elsewhere?

**Comment by willtp87** [comment]
Closing as per comments on the [pull](https://github.com/discoverygarden/islandora_collection_search/pull/14).
